"""model RandPresenter update column

Revision ID: d52e34c68e29
Revises: 038f1e0eb195
Create Date: 2024-01-30 16:29:14.501750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52e34c68e29'
down_revision: Union[str, None] = '038f1e0eb195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rand_presenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('presenter', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rand_presenters')
    # ### end Alembic commands ###
